#ifndef _AUTOCONFIG_H
#define _AUTOCONFIG_H
#define FOSSIL_CI_PFX "1205ec86cb55"
#define FOSSIL_DYNAMIC_BUILD 1
#define FOSSIL_ENABLE_SSL 1
#define FOSSIL_HAVE_GETPASS 1
#define HAVE_ARPA_NAMESER_H 1
#define HAVE_BACKTRACE 1
/* #undef HAVE_BIND_RESOLV_H */
#define HAVE_COMPRESSBOUND 1
#define HAVE_DLOPEN 1
/* #undef HAVE_DN_EXPAND */
/* #undef HAVE_EMSDK */
/* #undef HAVE_FUSE_MOUNT */
#define HAVE_GETHOSTBYNAME 1
#define HAVE_GETLOADAVG 1
#define HAVE_GETPASS 1
/* #undef HAVE_GETPASSPHRASE */
#define HAVE_ICONV 1
#define HAVE_INFLATEEND 1
#define HAVE_INT16_T 1
#define HAVE_INTTYPES_H 1
#define HAVE_NANOSLEEP 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NS_NAME_UNCOMPRESS 1
#define HAVE_NS_PARSERR 1
#define HAVE_OPENSSL_SSL_H 1
/* #undef HAVE_PLEDGE */
#define HAVE_PREAD 1
#define HAVE_RESOLV_H 1
/* #undef HAVE_RES_9_NS_INITPARSE */
/* #undef HAVE_RES_QUERY */
#define HAVE_SIN 1
#define HAVE_SOCKET 1
#define HAVE_SSL_NEW 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRCHRNUL 1
#define HAVE_UINT16_T 1
#define HAVE_UINT32_T 1
#define HAVE_UINT8_T 1
#define HAVE_UNISTD_H 1
#define HAVE_USLEEP 1
#define HAVE_UTIME 1
#define HAVE_ZLIB_H 1
#define HAVE___RES_QUERY 1
#define USE_LINENOISE 1
/* #undef USE_MMAN_H */
#define USE_PREAD 1
/* #undef USE_SEE */
/* #undef USE_SYSTEM_SQLITE */
#endif
